### ISSUE TITLE
"Undefined symbols for architecture x86_64" when building with 0.8.5

### ISSUE THREAD

**Issue by kirillzh** [touchlab/CrashKiOS#60]
Our project used to compile successfully with CrashKiOS 0.8.2 however when updating to 0.8.5 it now fails with:
```
06:36:18 > Task :shared:bugsnag:public:linkDebugTestIosX64 FAILED
06:36:18 e: /Applications/Xcode/14.2.0/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld invocation reported errors
06:36:18 
06:36:18 The /Applications/Xcode/14.2.0/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld command returned non-zero exit code: 1.
06:36:18 output:
06:36:18 Undefined symbols for architecture x86_64:
06:36:18   "_OBJC_CLASS_$_BugsnagHandledState", referenced from:
06:36:18       objc-class-ref in result.o
06:36:18 ld: symbol(s) not found for architecture x86_64
```

**Comment by kirillzh** [comment]
Build framework as static (with `isStatic = true`) worked.

**Comment by wellingtoncosta** [comment]
Hi @kirillzh! I'm closing this since you were able to make it.
